/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'add-category': RouteRecordInfo<'add-category', '/add-category', Record<never, never>, Record<never, never>>,
    'transaction': RouteRecordInfo<'transaction', '/add-transaction', Record<never, never>, Record<never, never>>,
    'categories': RouteRecordInfo<'categories', '/categories', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'echarts-test': RouteRecordInfo<'echarts-test', '/echarts-test', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'monthly-transactions': RouteRecordInfo<'monthly-transactions', '/monthly-transactions', Record<never, never>, Record<never, never>>,
    'more': RouteRecordInfo<'more', '/more', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    '/recurring-expenses/': RouteRecordInfo<'/recurring-expenses/', '/recurring-expenses', Record<never, never>, Record<never, never>>,
    '/recurring-expenses/edit/[expenseId]': RouteRecordInfo<'/recurring-expenses/edit/[expenseId]', '/recurring-expenses/edit/:expenseId', { expenseId: ParamValue<true> }, { expenseId: ParamValue<false> }>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
